# installation:
# create: mamba env create -f environment.yml
# activate: conda activate v2dl5
# update: mamba env update -f environment.yml --prune
#
name: v2dl5
channels:
  - conda-forge
dependencies:
  - astropy<6.0
  - astroquery
  - gammapy
  - matplotlib
  - pre-commit
  - pydantic<2
  - pyflakes
  - pytest
  - pytest-cov
  - pytest-xdist
  - python=3.11
  - scipy
