name: flake8 linter

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: linter
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
