---
name: CI-linting

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:

  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"


      - name: Check for non-ASCII characters
        run: |
          output=$(find . -type f \
          \( -name "*.py" -o -name "*.rst" -o -name "*.yml" -o -name "*.toml" \) \
          -exec perl -ne 'print if /[^[:ascii:]]/ && !/latin/i' {} \;)
          if [ -n "$output" ]; then
            echo "Non-ASCII characters found in documentation."
            exit 1
          fi

      - name: Install validation dependencies
        run: |
          pip install validate-pyproject

      - name: pyproject.toml
        run: |
          validate-pyproject pyproject.toml

      - name: Check whether the citation metadata from CITATION.cff is valid
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--validate"

      # Dependencies required to avoid errors
      # reported by linters
      - name: Install conda dependencies
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: v2dl5
          environment-file: environment.yml
          miniforge-version: latest
          channel-priority: strict
          auto-activate-base: false

      - name: Python dependencies
        run: |
          pip install -e '.[tests]' build

      - name: Build package
        run: python -m build

      - name: Install built wheel
        run: python -m pip install --force-reinstall --no-deps dist/*.whl

      - name: Check console-script entry points
        run: |
          v2dl5-add_spectral-fits-to-light-curve-table --help
          v2dl5-generate-run-list --help
          v2dl5-generate-run-lists-for-significant-points --help
          v2dl5-generate-run-lists-from-target-list --help
          v2dl5-grouped-time-bins --help
          v2dl5-nightly-time-bins --help
          v2dl5-plot-binary-light-curves --help
          v2dl5-print-simplified-light-curve --help
          v2dl5-reflected-region-analysis --help
          v2dl5-split-binary-run-list --help

      - name: Pre-commit
        run: |
          pre-commit run --all-files
