---
name: Unittests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: v2dl5
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Unit tests
        shell: bash -leo pipefail {0}
        env:
          PYTHONPATH: .
        run: pytest --durations=10 --color=yes .
